### ISSUE TITLE
Using another language (Dutch)

### ISSUE THREAD

**Issue by edloginova** [JulesBelveze/concepcy#15]
Hello,

I run into empty results when I try to use Concepcy with Dutch. Should it be done differently? This code does work if I switch to an English sentence and use `en_core_web_sm`.
SpaCy version: 3.4.1.
Python version: 3.8.0.
Thank you.

Code:

```
import spacy
import concepcy

nlp = spacy.load('nl_core_news_sm')
# Using default concepCy configuration
nlp.add_pipe('concepcy')
print(concepcy)
doc = nlp('Terwijl drugshandelaars de straten van Antwerpen onveilig maken, vindt hun handelswaar vlotjes de weg naar Vlamingen uit alle lagen van de bevolking.')

# Access all the 'RelatedTo' relations from the Doc
for word, relations in doc._.relatedto.items():
    print(f'Word: {word} {relations}')

# Access the 'RelatedTo' relations word by word
for token in doc:
    print(f'Word: {token} {token._.relatedto}')
```

Output:
```
Word: Terwijl []
Word: drugshandelaars []
Word: de []
Word: straten []
Word: van []
Word: Antwerpen []
Word: onveilig []
Word: maken []
Word: , []
Word: vindt []
Word: hun []
Word: handelswaar []
Word: vlotjes []
Word: de []
Word: weg []
Word: naar []
Word: Vlamingen []
Word: uit []
Word: alle []
Word: lagen []
Word: van []
Word: de []
Word: bevolking []
Word: . []
```

**Comment by JulesBelveze** [comment]
Hi @edloginova, good catch!

I am on holidays at the moment, so I cannot really dig into it right now. Have you tried with other Dutch sentences?? (could be that ConceptNet does not have enough "knowledge" on those specific words)

**Comment by edloginova** [comment]
Yes, though so, too, and tried a couple of them, like "De hond eet een appel en hij is er gek op", "Microsoft is een groot bedrijf dat in de VS is gevestigd", "Een vrouw draagt een diamant aan haar vinger.", but running into the same issue. Also just tried clean installation with Python 3.9, just in case, same thing.

**Comment by JulesBelveze** [comment]
Alright, I'll be back from holidays next week and will have a look at it 🙂
I'll keep you posted!

**Comment by JulesBelveze** [comment]
Hi @edloginova, I did some more investigations and I found out why you were not getting any results 😸 

It seems like in ConceptNet most of the `Edge.weight` in Dutch are `1.0`. However, the default concepCy configuration filters out relations with a weight lower than `2.0`.

I was able to get some some relations with the following custom configuration:
```
nlp.add_pipe(
     "concepcy",
     config={
         "relations_of_interest": ["RelatedTo"],
         "filter_edge_weight": 0.0,
         "filter_missing_text": False,
         "as_dict": False
     }
)
```
Let me know if it makes sense

**Comment by JulesBelveze** [comment]
Feel free to reopen it if the you find anything weird.

**Comment by edloginova** [comment]
Thank you a lot, makes sense! :)
